### ISSUE TITLE
Still valid?

### ISSUE THREAD

**Issue by pandalec** [judjdigj/Vulkan_in_Crostini#1]
Hey! Are these instructions still valid?

Currently trying out ChromeOS with Brunch Framework on a Desktop PC (Ryzen 3600 and RX 7800 XT). Tested it with the native Steam application and it works, but frames are significantly lower than under Linux. I am curious if I would get better results using Crostini?

BR

**Comment by judjdigj** [comment]
> Hey! Are these instructions still valid?
> 
> Currently trying out ChromeOS with Brunch Framework on a Desktop PC (Ryzen 3600 and RX 7800 XT). Tested it with the native Steam application and it works, but frames are significantly lower than under Linux. I am curious if I would get better results using Crostini?
> 
> BR

Afaik the Steam application works the same as crostini. They are both linux containers under VM. So performance loss is expected. However I'm not sure if the Brunch Framework really utilized RX7800XT.

**Comment by pandalec** [comment]
Thank you! Yeah performance was miserable, but funny though. Running a Windows Game in a Linux Container some how 3D accelerated on an Android like OS :)
